### ISSUE TITLE
1.1.7changelog

### ISSUE THREAD

**Issue by persistanceTube** [bougou/alertmanager-webhook-adapter#4]
大佬，可以介绍下1.1.7版本更新了什么吗？我看你的dockerhub上已经有1.1.7的镜像了，github上没有1.1.7的release

**Comment by bougou** [comment]
dockerhub 上的 1.1.7 版本应该是当前 github 最新的 master 的提交。与 1.1.6 版本相比，除了增加了一些调试用的代码外，暂无其它的改动；从用户使用角度看，应该没有区别。

注意，后面 github 上发布 1.1.7 版本时，可能会覆盖 dockerhub 上的 1.1.7 镜像，所以目前你可以直接用 1.1.6 镜像。

**Comment by persistanceTube** [comment]
好的，感谢解答，还有一个问题是成功发送消息通知服务不会输出日志吗？

**Comment by bougou** [comment]
1.1.6 版本还没有输出日志，后面会加。

**Comment by zzwwzh** [comment]
大佬，可以增加设置代理proxy的功能吗，实际工作中使用，难免会有网络管控，需要走代理

**Comment by bougou** [comment]
> 大佬，可以增加设置代理proxy的功能吗，实际工作中使用，难免会有网络管控，需要走代理

程序应该会自动识别系统环境变量 HTTP_PROXY，HTTPS_PROXY。
