### ISSUE TITLE
docker安装

### ISSUE THREAD

**Issue by Trimblex** [bougou/alertmanager-webhook-adapter#5]
请问大佬有没有docker的容器运行手册呢

**Comment by bougou** [comment]
Try like this:

```bash

docker run --rm -it -p 127.0.0.1:8090:8090 bougou/alertmanager-webhook-adapter:v1.1.7

# specify options
docker run --rm -it -p 127.0.0.1:8090:8090 bougou/alertmanager-webhook-adapter:v1.1.7 --signature MyIDC --debug
```

**Comment by Trimblex** [comment]
> 试试这个：
> 
> ```shell
> docker run --rm -it -p 127.0.0.1:8090:8090 bougou/alertmanager-webhook-adapter:v1.1.7
> 
> # specify options
> docker run --rm -it -p 127.0.0.1:8090:8090 bougou/alertmanager-webhook-adapter:v1.1.7 --signature MyIDC --debug
> ```

thanks for it, maybe "--signature MyIDC" is the key hah
